Update 'prepare_managed_clusters_data' to pass with args set to None value
RedHatQE/openshift-cli-installer pull request #186
Opened 2023-09-20 18:22 UTC by oharan2

When gcp_service_account_file is None, `get_service_account_dict_from_file` fails when unneeded (for example a ROSA cluster)

Prow testing failure example:
`TypeError: expected str, bytes or os.PathLike object, not NoneType`
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/43065/rehearse-43065-pull-ci-rhpit-interop-tests-main-rosa-sts-test-rhods-operator-4.13-lp-rosa-rosa-sts-rhods-test-operator/1704533939206492160#1:build-log.txt%3A114

2023-09-20 18:31 UTC, rnetser requested changes

2023-09-20 18:31 UTC, rnetser commented on openshift_cli_installer/libs/managed_clusters/helpers.py
> +            if gcp_service_account_file:
please remove, this is checked in https://github.com/RedHatQE/openshift-cli-installer/blob/main/openshift_cli_installer/utils/cli_utils.py#L472

2023-09-20 18:31 UTC, rnetser commented on openshift_cli_installer/libs/managed_clusters/helpers.py
> +                raise click.Abort()
ditto

2023-09-20 18:48 UTC, oharan2 commented on openshift_cli_installer/libs/managed_clusters/helpers.py
>      aws_access_key_id,
Done

2023-09-20 18:54 UTC, rnetser requested changes

2023-09-21 06:16 UTC, oharan2 commented
Resolved in #190

2023-09-21 06:16 UTC, closed without merging