Refactor tts function
RedHatQE/openshift-cli-installer pull request #47
Opened 2023-07-30 15:38 UTC by oharan2

A small refactor suggestion, make better tolerance with phrases like "1.5H"
current implement will try to return an int when it gets invalid phrase like "H1"

2023-07-30 16:30 UTC, myakove reviewed
In the current implementation we do not raise unless the original value is not int. (Let int() do the raise if needed)

We do not support 1.5H, if the user want 1.5H the user should send 90m

2023-08-01 12:14 UTC, oharan2 commented
> In the current implementation we do not raise unless the original value is not int. (Let int() do the raise if needed)
> 
> We do not support 1.5H, if the user want 1.5H the user should send 90m

Done
Updated with just making it more strict towards the input
PR description is updated

2023-08-01 12:14 UTC, oharan2 commented
/verified

2023-08-01 12:15 UTC, oharan2 commented
/verified

2023-08-01 14:50 UTC, myakove requested changes
Let's keep it simple, we only accept:
`(number)/s/m/h` or `int` 
No need to get all permutation, the user should know how to use this function (docstring)

2023-08-02 09:18 UTC, omrirh approved these changes

2023-08-02 13:06 UTC, oharan2 commented
/verified

2023-08-04 21:38 UTC, myakove commented
/retest sonarqube

2023-08-04 21:42 UTC, myakove requested changes

2023-08-04 21:42 UTC, myakove commented on app/libs/rosa_clusters.py
> +        print(
You need to return `int(ts)` here.

2023-08-04 21:42 UTC, myakove commented on app/libs/rosa_clusters.py
> +    return int(_val)
just `return int(_val) * time_ref[_unit]`

2023-08-04 21:58 UTC, myakove commented
/retest sonarqube

2023-08-07 08:03 UTC, oharan2 commented
> You need to return `int(ts)` here.

If we will keep the regex 'strictness' and the exception handling in the same way as before,
I'm closing since i'm not seeing added value in my changes.

2023-08-07 08:03 UTC, closed without merging