Add option to uninstall all clusters
RedHatQE/openshift-cli-installer pull request #58
Opened 2023-07-31 15:27 UTC by rnetser

2023-08-05 13:57 UTC, myakove commented
/retest sonarqube

2023-08-07 08:32 UTC, omrirh approved these changes

2023-08-08 08:17 UTC, oharan2 approved these changes

2023-08-08 10:43 UTC, rnetser commented
/wip

2023-08-09 08:33 UTC, rnetser commented
/retest sonarqube

2023-08-09 08:33 UTC, rnetser commented
/wip cancel

2023-08-09 08:58 UTC, myakove requested changes

2023-08-09 08:58 UTC, myakove commented on app/cli.py
> +        return
better to `return destroy_clusters`, move the return to line 307

2023-08-09 08:58 UTC, myakove commented on app/libs/destroy_clusters.py
> +def _destroy_clusters_download_installer_binary(
The name is confusing, when reading this I this you will destroy the binaries directories.

2023-08-09 08:58 UTC, myakove commented on app/libs/destroy_clusters.py
> +    for cluster_type in cluster_data_dict:
`cluster_data_dict.items()` ?

2023-08-09 08:58 UTC, myakove commented on app/libs/destroy_clusters.py
> +                cluster_data=cluster_data, action="destroy"
`"destroy"` should be constant

2023-08-09 08:58 UTC, myakove commented on app/libs/destroy_clusters.py
> +        _data["install-dir"] = root
you should get `root` as `_root` in the inner function

2023-08-09 12:00 UTC, rnetser commented
/retest build-container

2023-08-09 12:01 UTC, rnetser commented
/verified

2023-08-09 12:04 UTC, rnetser commented
/retest sonarqube

2023-08-09 12:07 UTC, myakove approved these changes

2023-08-09 12:08 UTC, merged