Fix manifest path for run from container
RedHatQE/openshift-cli-installer pull request #98
Opened 2023-08-16 17:01 UTC by myakove

2023-08-16 17:12 UTC, rnetser requested changes

2023-08-16 17:12 UTC, rnetser commented on openshift_cli_installer/libs/rosa_clusters.py
> +        manifests_path = "openshift_cli_installer/manifests"
should be extracted to function

2023-08-16 17:12 UTC, rnetser commented on openshift_cli_installer/libs/rosa_clusters.py
> +        terraform.plan("rosa.plan")
ok to drop the arg name?

2023-08-16 18:43 UTC, myakove commented
/verified

2023-08-16 19:06 UTC, myakove commented on openshift_cli_installer/libs/rosa_clusters.py
> +        terraform.plan("rosa.plan")
added again

2023-08-16 19:07 UTC, myakove commented
/verified

2023-08-16 19:15 UTC, myakove commented
/verified

2023-08-16 19:40 UTC, rnetser requested changes

2023-08-16 19:40 UTC, rnetser commented on openshift_cli_installer/libs/rosa_clusters.py
> +            f"Create hypershift PVC for cluster {cluster_data['name']} failed, rolling back."
```suggestion
            f"Create hypershift VPC for cluster {cluster_data['name']} failed, rolling back."
```

2023-08-16 19:46 UTC, rnetser requested changes

2023-08-16 19:46 UTC, rnetser commented on openshift_cli_installer/libs/rosa_clusters.py
> +    click.echo(f"Destroy hypershift PVC for cluster {cluster_data['name']}")
```suggestion
    click.echo(f"Destroy hypershift VPC for cluster {cluster_data['name']}")
```

2023-08-16 19:46 UTC, rnetser commented on openshift_cli_installer/libs/rosa_clusters.py
> +        click.echo(f"Preparing hypershift PVC for cluster {cluster_data['name']}")
```suggestion
        click.echo(f"Preparing hypershift VPC for cluster {cluster_data['name']}")
```

2023-08-16 19:55 UTC, myakove commented
/verified

2023-08-17 06:04 UTC, rnetser commented on openshift_cli_installer/libs/rosa_clusters.py
> +        destroy_hypershift_vpc(cluster_data=cluster_data)
should also call here `delete_oidc`

2023-08-17 07:36 UTC, rnetser approved these changes

2023-08-17 07:36 UTC, merged